---
title: Finding text between patterns with regex and Python
hero_image: images/banner.png
description: Finding text between patterns with regex
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
site_areas:
steps:
  - 
    title: Finding text
